<?php
/**
 * $Id: taxonomy_defaults.install,v 1.2 2006/11/14 08:16:49 heine Exp $ 
 *
 * 
 * 
 * Drupal version: 
 * 
 * @author: Heine Deelstra
 */

/**
 * Hook sets taxonomy_defaults 'weight' to -1. This ensures that it's hook_form_alter runs before taxonomy
 * 
 */
function taxonomy_defaults_install() {
  $ret = array();
  $ret[] = db_query("UPDATE {system} SET weight = -1 WHERE name = 'taxonomy_defaults'");
  return $ret;
}
